import os
import esphome.codegen as cg
import esphome.config_validation as cv
from esphome import pins
from esphome.components import spi
from esphome.const import CONF_ID
from esphome.core import CORE

DEPENDENCIES = ["spi"]

elero_ns = cg.esphome_ns.namespace("elero")
elero = elero_ns.class_("Elero", spi.SPIDevice, cg.Component)

CONF_GDO0_PIN = "gdo0_pin"
CONF_ELERO_ID = "elero_id"
CONF_FREQ0 = "freq0"
CONF_FREQ1 = "freq1"
CONF_FREQ2 = "freq2"
CONF_LOGGING = "logging"
CONF_LOGGING_ENABLE = "enable"
CONF_LOGGING_MAX_ENTRIES = "max_entries"

LOGGING_SCHEMA = cv.Schema(
    {
        cv.Optional(CONF_LOGGING_ENABLE, default=True): cv.boolean,
        cv.Optional(CONF_LOGGING_MAX_ENTRIES, default=1000): cv.int_range(min=100, max=5000),
    }
)

CONFIG_SCHEMA = (
    cv.Schema(
        {
            cv.GenerateID(): cv.declare_id(elero),
            cv.Required(CONF_GDO0_PIN): pins.gpio_input_pin_schema,
            cv.Optional(CONF_FREQ0, default=0x7a): cv.hex_int_range(min=0x0, max=0xff),
            cv.Optional(CONF_FREQ1, default=0x71): cv.hex_int_range(min=0x0, max=0xff),
            cv.Optional(CONF_FREQ2, default=0x21): cv.hex_int_range(min=0x0, max=0xff),
            cv.Optional(CONF_LOGGING): LOGGING_SCHEMA,
        }
    )
    .extend(cv.COMPONENT_SCHEMA)
    .extend(spi.spi_device_schema(cs_pin_required=True))
)

# Partition table (4 MB flash, OTA + LittleFS).
# Used automatically for IDF builds; Arduino uses the built-in 'default.csv'.
# Users can override with platformio_options: board_build.partitions: in YAML.
_PARTITIONS_4MB_CSV = """\
# Auto-generated by esphome-elero — 4 MB flash with OTA + LittleFS (SPIFFS partition)
# Override: add  platformio_options:\n#             board_build.partitions: your_table.csv  to your ESPHome YAML.
# Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,     0x9000,  0x5000,
otadata,  data, ota,     0xe000,  0x2000,
app0,     app,  ota_0,   0x10000, 0x140000,
app1,     app,  ota_1,   0x150000,0x140000,
spiffs,   data, spiffs,  0x290000,0x170000,
"""


def _ensure_elero_partitions_csv():
    """Write elero_partitions.csv next to the user's YAML config (if absent).

    Returns the absolute path so PlatformIO can locate it regardless of the
    working directory used during the build.
    """
    config_dir = os.path.dirname(os.path.abspath(CORE.config_path))
    csv_path = os.path.join(config_dir, "elero_partitions.csv")
    if not os.path.exists(csv_path):
        with open(csv_path, "w") as f:
            f.write(_PARTITIONS_4MB_CSV)
    return csv_path


async def to_code(config):
    var = cg.new_Pvariable(config[CONF_ID])
    await cg.register_component(var, config)
    await spi.register_spi_device(var, config)

    gdo0_pin = await cg.gpio_pin_expression(config[CONF_GDO0_PIN])
    cg.add(var.set_gdo0_pin(gdo0_pin))
    cg.add(var.set_freq0(config[CONF_FREQ0]))
    cg.add(var.set_freq1(config[CONF_FREQ1]))
    cg.add(var.set_freq2(config[CONF_FREQ2]))

    # LittleFS is always required: EleroStorage persists runtime-adopted blinds,
    # RF packet dumps, and blind state snapshots regardless of whether the
    # optional persistent event log is enabled.
    if CORE.using_arduino:
        cg.add_library("LittleFS", None)
        # 'default.csv' is bundled with arduino-esp32 / PlatformIO and provides
        # nvs + otadata + app0 + app1 + spiffs on standard 4 MB boards.
        # Users with 8 MB / 16 MB flash should override this via:
        #   platformio_options:
        #     board_build.partitions: default_8MB.csv
        cg.add_platformio_option("board_build.partitions", "default.csv")

    if CORE.using_esp_idf:
        cg.add_platformio_option(
            "lib_deps", ["https://github.com/joltwallet/esp_littlefs.git"]
        )
        # joltwallet/esp_littlefs expects Kconfig-generated CONFIG_LITTLEFS_*
        # defines.  When pulled as a PlatformIO lib_dep the Kconfig system does
        # not run, so we supply the defaults as build flags.
        for flag in [
            "-DCONFIG_LITTLEFS_MAX_PARTITIONS=3",
            "-DCONFIG_LITTLEFS_PAGE_SIZE=256",
            "-DCONFIG_LITTLEFS_READ_SIZE=128",
            "-DCONFIG_LITTLEFS_WRITE_SIZE=128",
            "-DCONFIG_LITTLEFS_LOOKAHEAD_SIZE=128",
            "-DCONFIG_LITTLEFS_CACHE_SIZE=512",
            "-DCONFIG_LITTLEFS_BLOCK_CYCLES=512",
            "-DCONFIG_LITTLEFS_OBJ_NAME_LEN=64",
        ]:
            cg.add_build_flag(flag)
        # Generate a partition CSV with a SPIFFS partition next to the YAML and
        # point PlatformIO at it via an absolute path.
        csv_path = _ensure_elero_partitions_csv()
        cg.add_platformio_option("board_build.partitions", csv_path)

    if CONF_LOGGING in config:
        log_conf = config[CONF_LOGGING]
        if log_conf[CONF_LOGGING_ENABLE]:
            cg.add(var.set_persistent_log_enabled(True))
            cg.add(var.set_persistent_log_max_entries(log_conf[CONF_LOGGING_MAX_ENTRIES]))
            # Ensure LittleFS library is available for persistent logging
            if CORE.using_arduino:
                cg.add_library("LittleFS", None)
            if CORE.using_esp_idf:
                cg.add_platformio_option(
                    "lib_deps", ["https://github.com/joltwallet/esp_littlefs.git"]
                )
