version: 2

multi-ecosystem-groups:
  monthly-dependencies:
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "monthly-dependencies"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/components/elero_web/frontend"
    patterns:
      - "*"
    multi-ecosystem-group: "monthly-dependencies"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/components/elero_web/frontend-legacy"
    patterns:
      - "*"
    multi-ecosystem-group: "monthly-dependencies"
    cooldown:
      default-days: 3
    open-pull-requests-limit: 1
